name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout.
      uses: actions/checkout@v2
      
    - name: Build.
      run: g++ main.cpp -o run
    
    - name: Upload.
      uses: actions/upload-artifact@v1.0.0
      with:
        name: run
        path: run
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled artifact.
        uses: actions/download-artifact@v1.0.0
        with:
          name: run
          path: run
      - name : Run it.
        run: echo "1000000" | ./run
